### ISSUE TITLE
Table of contents end tag

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/api-playbook#8]
I'm not sure what sort of ToC generation we're using here, but the end tag remains visible in the README:

![screen shot 2015-06-10 at 13 39 50](https://cloud.githubusercontent.com/assets/378235/8081575/3b4014e0-0f76-11e5-923e-17aa90904ce0.png)

**Comment by fespinoza** [comment]
i generated it with an atom plugin, on the atom preview it doesn't show the comment at the end

**Comment by timkurvers** [comment]
It seems that adding a blank line in between the last list item and the end tag fixes it. Would that work correctly for your Atom plugin @fespinoza?

**Comment by fespinoza** [comment]
maybe, if not we remove it anyway
